"""add_document_versioning_and_tags

Revision ID: 0752c2d6bc3f
Revises: 002
Create Date: 2025-08-23 10:01:50.347131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0752c2d6bc3f'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values for existing data
    op.add_column('knowledge_documents', sa.Column('original_name', sa.String(length=255), nullable=True))
    op.add_column('knowledge_documents', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('knowledge_documents', sa.Column('parent_document_id', sa.UUID(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('knowledge_documents', sa.Column('tags', sa.String(length=500), nullable=True))
    
    # Update original_name for existing documents to use file_name
    op.execute("UPDATE knowledge_documents SET original_name = file_name WHERE original_name IS NULL")
    
    # Now make original_name not nullable
    op.alter_column('knowledge_documents', 'original_name', nullable=False)
    
    # Create foreign key constraint
    op.create_foreign_key('fk_parent_document', 'knowledge_documents', 'knowledge_documents', ['parent_document_id'], ['id'])
    
    # Recreate the vector index if it doesn't exist
    op.execute('CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding ON document_chunks USING hnsw (embedding vector_l2_ops)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_parent_document', 'knowledge_documents', type_='foreignkey')
    op.drop_column('knowledge_documents', 'tags')
    op.drop_column('knowledge_documents', 'content_hash')
    op.drop_column('knowledge_documents', 'file_size')
    op.drop_column('knowledge_documents', 'parent_document_id')
    op.drop_column('knowledge_documents', 'version')
    op.drop_column('knowledge_documents', 'original_name')
    # ### end Alembic commands ###