"""Add user names, shared documents, document processing params, and model management

Revision ID: 4a2466e9a208
Revises: 0752c2d6bc3f
Create Date: 2025-08-23 16:52:41.982327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2466e9a208'
down_revision = '0752c2d6bc3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    # Add columns with default values first
    op.add_column('document_chunks', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.execute("UPDATE document_chunks SET is_shared = false WHERE is_shared IS NULL")
    op.alter_column('document_chunks', 'is_shared', nullable=False)
    
    op.alter_column('document_chunks', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Drop index if it exists
    try:
        op.drop_index('idx_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw')
    except:
        pass
    
    # Add columns to knowledge_documents
    op.add_column('knowledge_documents', sa.Column('is_shared', sa.Boolean(), nullable=True))
    op.execute("UPDATE knowledge_documents SET is_shared = false WHERE is_shared IS NULL")
    op.alter_column('knowledge_documents', 'is_shared', nullable=False)
    
    op.add_column('knowledge_documents', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('overlap_length', sa.Integer(), nullable=True))
    op.alter_column('knowledge_documents', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Add name column to users with default value
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET name = 'User ' || employee_id WHERE name IS NULL")
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.alter_column('knowledge_documents', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('knowledge_documents', 'overlap_length')
    op.drop_column('knowledge_documents', 'chunk_size')
    op.drop_column('knowledge_documents', 'is_shared')
    op.create_index('idx_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('document_chunks', 'is_shared')
    op.drop_table('llm_models')
    # ### end Alembic commands ###